export const featuresList = [
  "Added Firebase Authentication",
  "Fetching restaurant data from API",
  "Rendered data using react-hooks with cool stylings.",
  "Added banner for food-items",
  "Made Sticky Navbar",
  "User can fetch data according to pincode",
  "User can search for particular food in top restaurant",
  "User can search restaurants using the search option available in navbar.",
  "Added filters(rate, cost, delivery time) in available restaurants",
  "Added a cool footer where all cities are listed.",
  "User can get data of each Restaurant by clicking on it.",
  "Implement lazy loading.",
  "Added categories for each particular restaurant dynamically.",
  "Added accordian functionality in categories.",
  "User can add food item to cart and can modify it from cart itself.",
  "The most powerful thing added is the react-redux and redux-tooklit.",
  "All cart data, user location, login, logout everything is controlled from it.",
];
